# Generated by Django 5.0.1 on 2024-01-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_alter_movies_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='img',
            field=models.ImageField(default='helo', upload_to='pics'),
            preserve_default=False,
        ),
    ]
